import {it,afterEach} from 'node:test';import {strictEqual,ok,match} from 'node:assert';
import {mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,symlinkSync,existsSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import {randomUUID} from 'node:crypto';import {spawnSync} from 'node:child_process';
import {preparePlanClaim} from '../src/pickup.mjs';import {mutateFileSet} from '../src/atomic-mutation.mjs';
import {startApp} from '../src/app.mjs';import {resolveConfig} from '../src/config.mjs';import {deriveFlags,readFlagEvents} from '../src/flags.mjs';
import {createDocumentLibrary} from '../src/app-library.mjs';import {createRecordLibrary} from '../src/app-records.mjs';import {sourceRevision} from '../src/source-editor.mjs';
const dirs=[],apps=[],bin=path.resolve(import.meta.dirname,'../bin/runlist.mjs');afterEach(async()=>{for(const app of apps.splice(0))await app.close();for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
const source='---\ntype: plan\nstatus: active\nparent_plan: hub.md\ncustom: kept\n---\n# Fixture plan\n\nF1 concerns `src/fixture.mjs`.\n\n## Decisions\n\n### D1 Which bin?\nDisposition: OPEN.\n\nQuestion: Which bin should carry the work?\nAlternatives: Blue or red.\nConsequences: Blue fits, red needs a new shelf.\n\n## Version History\n\n- Earlier entry.\n';
it('record refresh retains a concurrent invalidation and coalesces readers onto the current source',async()=>{
 const root=mkdtempSync(path.join(os.tmpdir(),'runlist-record-race-'));dirs.push(root);mkdirSync(path.join(root,'docs'));writeFileSync(path.join(root,'runlist.config.mjs'),"export const root='docs';\n");const file=path.join(root,'docs/plan.md');writeFileSync(file,source);
 const config=await resolveConfig(root),library=createDocumentLibrary(config);let records,reads=0;
 records=createRecordLibrary({config,library,evidence:()=>({}),readSource:(_context,p)=>{
  const raw=readFileSync(path.join(root,p),'utf8');reads++;
  if(reads===1){writeFileSync(file,source.replaceAll('Which bin','Updated bin'));library.invalidate(p);records.invalidate();}
  return {source:raw,revision:sourceRevision(raw),editable:true,path:p};
 }});
 const replies=await Promise.all([records.query({},'decisions',new URLSearchParams()),records.query({},'decisions',new URLSearchParams())]);
 for(const reply of replies){strictEqual(reply.total,1);match(reply.records[0].title,/Updated bin/);}
 strictEqual(reads,2);strictEqual(library.stats.fullScans,1);
});
async function fixture(){const repo=mkdtempSync(path.join(os.tmpdir(),'runlist-records-'));dirs.push(repo);for(const d of ['docs/plans','docs/prompts','src','.runlist'])mkdirSync(path.join(repo,d),{recursive:true});writeFileSync(path.join(repo,'runlist.config.mjs'),"export const root='docs';\n");writeFileSync(path.join(repo,'docs/plans/fixture.md'),source);writeFileSync(path.join(repo,'docs/plans/hub.md'),'---\ntype: plan\nstatus: active\nexecution_mode: coordination\nrunlist: [fixture.md]\n---\n# Fixture hub\n');writeFileSync(path.join(repo,'docs/prompts/private.md'),'---\ntype: prompt\nstatus: pending\n---\nPRIVATE FIXTURE\n');writeFileSync(path.join(repo,'src/fixture.mjs'),'// shifted\nconst observed = true;\n');const log=path.join(repo,'.runlist/flags.jsonl'),add={event:'add',id:'F1',at:'2026-10-05T00:00:00Z',file:'src/fixture.mjs',line:1,quote:'const observed = true;',text:'Keep the finding and its evidence.',severity:'problem',by:{kind:'check',name:'fixture'}};writeFileSync(log,JSON.stringify(add)+'\n');const app=await startApp({config:await resolveConfig(repo),port:0,actor:{kind:'human',id:'human:fixture',label:'Fixture owner'}});apps.push(app);const token=new URLSearchParams(new URL(app.launchUrl).hash.slice(1)).get('connect'),res=await fetch(app.origin+'/api/session',{method:'POST',headers:{Origin:app.origin,'Content-Type':'application/json'},body:JSON.stringify({token})}),cookie=res.headers.get('set-cookie').split(';')[0],session=await res.json();const call=async(route,body,headers={})=>{const res=await fetch(app.origin+'/api/'+route,{method:body===undefined?'GET':'POST',headers:{Cookie:cookie,Origin:app.origin,'Content-Type':'application/json','X-Runlist-CSRF':session.csrf,...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:res.status,value:await res.json()};};return {repo,config:await resolveConfig(repo),log,add,call,file:path.join(repo,'docs/plans/fixture.md')};}
it('homes real flags and decisions with filters, original/current evidence and parent hub links',async()=>{const f=await fixture();const flags=(await f.call('records?kind=flags')).value;strictEqual(flags.total,1);strictEqual(flags.counts.decisions,1);const flag=(await f.call('records?kind=flags&key=F1')).value;strictEqual(flag.current.status,'moved');strictEqual(flag.original.line,1);strictEqual(flag.current.line,2);ok(flag.connections.some(c=>c.path==='docs/plans/hub.md'),JSON.stringify(flag.connections));const ds=(await f.call('records?kind=decisions')).value;strictEqual(ds.total,1);ok(ds.records[0].title.includes('Which bin'));strictEqual((await f.call('records?kind=flags&severity=info')).value.total,0);strictEqual((await f.call('records?kind=decisions&scope=docs/plans/hub.md')).value.total,1);ok(!JSON.stringify(ds).includes('PRIVATE FIXTURE'));});
it('triage is append-only, scoped to the trusted human, revision checked and retry safe',async()=>{const f=await fixture(),flag=(await f.call('records?kind=flags&key=F1')).value,before=readFileSync(f.log,'utf8'),request={key:'F1',action:'accept',note:'This needs work.',operationId:randomUUID(),expectedRevision:flag.revision,actor:{kind:'agent',id:'forged'}};strictEqual((await f.call('flags/triage',request,{'X-Runlist-CSRF':''})).status,403);strictEqual((await f.call('flags/triage',request)).status,403);strictEqual(readFileSync(f.log,'utf8'),before);delete request.actor;const first=await f.call('flags/triage',request);strictEqual(first.status,200,JSON.stringify(first));ok(readFileSync(f.log,'utf8').startsWith(before));strictEqual(first.value.history[0].by.id,'human:fixture');strictEqual((await f.call('flags/triage',request)).value.replayed,true);strictEqual(readFlagEvents(f.log).length,2);strictEqual((await f.call('flags/triage',{...request,operationId:randomUUID(),action:'resolve'})).value.code,'flag-revision-conflict');strictEqual((await f.call('flags/triage',{...request,note:'Changed request'})).value.code,'flag-operation-reused');const current=(await f.call('records?kind=flags&key=F1')).value;strictEqual((await f.call('flags/triage',{...request,action:'resolve',expectedRevision:current.revision,operationId:randomUUID()})).status,200);strictEqual(deriveFlags(readFlagEvents(f.log))[0].history.length,2);strictEqual((await f.call('records?kind=flags')).value.total,0);});
it('reviews and saves a human ruling without erasing old source, retries safely and the CLI reads it',async()=>{const f=await fixture(),row=(await f.call('records?kind=decisions')).value.records[0],record=(await f.call('records?'+new URLSearchParams({kind:'decisions',key:row.key}))).value,requestPreview={key:row.key,expectedRevision:record.revision,disposition:'ruled',note:'It fits.',choice:'Blue bin'};strictEqual((await f.call('decisions/preview',{...requestPreview,actor:{kind:'agent',id:'forged'}})).status,403);strictEqual(readFileSync(f.file,'utf8'),source);const preview=await f.call('decisions/preview',requestPreview);strictEqual(preview.status,200,JSON.stringify(preview));strictEqual(readFileSync(f.file,'utf8'),source);match(preview.value.source,/Recorded by Fixture owner \(human\)/);const request={...preview.value,operationId:randomUUID()};strictEqual((await f.call('save',request)).status,200);strictEqual((await f.call('save',request)).value.replayed,true);strictEqual(readFileSync(f.file,'utf8'),preview.value.source);ok(preview.value.source.includes('Disposition: OPEN.'));ok(preview.value.source.endsWith('## Version History\n\n- Earlier entry.\n'));const cli=spawnSync(process.execPath,[bin,'decisions','--all','--json'],{cwd:f.repo,encoding:'utf8'});strictEqual(cli.status,0,cli.stderr);const rows=JSON.parse(cli.stdout);strictEqual(rows[0].disposition,'ruled');strictEqual((await f.call('records?kind=decisions')).value.total,0);});
it('refuses stale decision previews and reviewed writes after external source changes',async()=>{const f=await fixture(),row=(await f.call('records?kind=decisions')).value.records[0],record=(await f.call('records?'+new URLSearchParams({kind:'decisions',key:row.key}))).value,preview=(await f.call('decisions/preview',{key:row.key,expectedRevision:record.revision,disposition:'held',note:'Need evidence.'})).value;writeFileSync(f.file,source+'\nExternal change.\n');strictEqual((await f.call('decisions/preview',{key:row.key,expectedRevision:record.revision,disposition:'held',note:'Need evidence.'})).value.code,'decision-revision-conflict');strictEqual((await f.call('save',{...preview,operationId:randomUUID()})).value.code,'revision-conflict');ok(readFileSync(f.file,'utf8').includes('External change.'));});
it('filters prompt findings and refuses a journal symlink outside the checkout',async()=>{const f=await fixture();writeFileSync(f.log,readFileSync(f.log,'utf8')+JSON.stringify({...f.add,id:'F2',file:'docs/prompts/private.md',text:'PRIVATE FIXTURE'})+'\n');strictEqual((await f.call('records?kind=flags')).value.total,1);const outside=mkdtempSync(path.join(os.tmpdir(),'runlist-record-outside-'));dirs.push(outside);writeFileSync(path.join(outside,'flags.jsonl'),JSON.stringify(f.add)+'\n');rmSync(f.log);symlinkSync(path.join(outside,'flags.jsonl'),f.log);strictEqual((await f.call('records?kind=flags')).status,400);});
it('CLI shares outcome preparation, checks human versus agent and leaves no writes on dry-run',async()=>{const f=await fixture(),env={...process.env};for(const k of Object.keys(env))if(/SESSION|^CODEX_|^OPENCODE_|^RUNLIST_|^DOTMD_/.test(k))delete env[k];const args=['decision','docs/plans/fixture.md','D1','--disposition','ruled','--choice','Blue bin','--note','It fits.'];const dry=spawnSync(process.execPath,[bin,...args,'--dry-run'],{cwd:f.repo,env,encoding:'utf8'});strictEqual(dry.status,0,dry.stderr);match(dry.stdout,/Disposition: RULED/);strictEqual(readFileSync(f.file,'utf8'),source);strictEqual(existsSync(path.join(f.repo,'.runlist/source-editor')),false);const agent=spawnSync(process.execPath,[bin,...args],{cwd:f.repo,env:{...env,RUNLIST_SESSION_ID:'fixture-agent'},encoding:'utf8'});ok(agent.status!==0);match(agent.stderr,/human/);const saved=spawnSync(process.execPath,[bin,...args,'--json'],{cwd:f.repo,env,encoding:'utf8'});strictEqual(saved.status,0,saved.stderr);strictEqual(JSON.parse(saved.stdout).actor.kind,'human');match(readFileSync(f.file,'utf8'),/Disposition: RULED/);});

it('explains a claimed decision and refuses its preview while preserving the owned source',async()=>{const f=await fixture(),row=(await f.call('records?kind=decisions')).value.records[0],before=(await f.call('records?'+new URLSearchParams({kind:'decisions',key:row.key}))).value;const claim=preparePlanClaim({filePath:f.file,sourceContent:source,renderedContent:null,ownership:null,sessionId:'fixture-agent-owner',now:'2026-10-05T00:00:00Z',config:f.config});mutateFileSet(claim,{repoRoot:f.repo});const claimed=(await f.call('records?'+new URLSearchParams({kind:'decisions',key:row.key}))).value;strictEqual(claimed.editable,false);match(claimed.readOnlyReason,/fixture-agent-owner/);strictEqual((await f.call('decisions/preview',{key:row.key,expectedRevision:before.revision,disposition:'held',note:'Reason'})).value.code,'record-read-only');strictEqual(readFileSync(f.file,'utf8'),source);});
it('indexes exact flag IDs, overlapping IDs and paths, including journal additions between refreshes',async()=>{
 const f=await fixture();
 const additions=[{...f.add,id:'F10',file:'src/ten.mjs'},{...f.add,id:'F1-extra',file:'src/extra.mjs'},{...f.add,id:'F2',file:'src/nested'},{...f.add,id:'F3',file:'src/nested/file.mjs'}];
 writeFileSync(f.log,[f.add,...additions].map(event=>JSON.stringify(event)).join('\n')+'\n');
 writeFileSync(path.join(f.repo,'docs/plans/ten.md'),'---\ntype: plan\nstatus: active\n---\n# Ten\n\nF10 only.\n');
 writeFileSync(path.join(f.repo,'docs/plans/overlap.md'),'---\ntype: plan\nstatus: active\n---\n# Overlap\n\nF1-extra, src/nested/file.mjs, F99.\n');
 const rows=(await f.call('records?kind=flags&refresh=1')).value.records;
 const detail=async id=>(await f.call('records?'+new URLSearchParams({kind:'flags',key:rows.find(row=>row.id===id).key}))).value;
 strictEqual((await detail('F1')).connections.some(c=>c.path==='docs/plans/ten.md'),false);
 for(const id of ['F1','F1-extra','F2','F3'])ok((await detail(id)).connections.some(c=>c.path==='docs/plans/overlap.md'),id);
 strictEqual((await f.call('records?'+new URLSearchParams({kind:'flags',scope:'docs/plans/overlap.md'}))).value.total,4);
 writeFileSync(f.log,readFileSync(f.log,'utf8')+JSON.stringify({...f.add,id:'F99',file:'src/new.mjs'})+'\n');
 const added=(await f.call('records?'+new URLSearchParams({kind:'flags',key:'F99'}))).value;
 ok(added.connections.some(c=>c.path==='docs/plans/overlap.md'));
});
it('indexes same-offset prefixes and overlapping path suffixes with literal punctuation',async()=>{
 const f=await fixture(),paths=['src/part[1].mjs','src/part[1].mjs.map','part[1].mjs'];
 writeFileSync(f.log,paths.map((file,i)=>JSON.stringify({...f.add,id:'F'+(i+10),file})).join('\n')+'\n');
 writeFileSync(f.file,source+'\nObserved src/part[1].mjs.map.\n');
 const rows=(await f.call('records?kind=flags&refresh=1')).value.records;
 for(const row of rows){const detail=(await f.call('records?'+new URLSearchParams({kind:'flags',key:row.key}))).value;ok(detail.connections.some(c=>c.path==='docs/plans/fixture.md'),row.id);}
});
it('loads linked decision bodies on demand and refuses a moved peer until refreshed',async()=>{
 const f=await fixture(),peer=path.join(f.repo,'docs/plans/peer.md');
 writeFileSync(f.file,source.replace('Alternatives: Blue or red.','Alternatives: Blue or red.\nOriginal peer evidence.\nD1 in [peer](peer.md).'));
 const peerSource='---\ntype: plan\nstatus: active\n---\n# Peer\n\n## Decisions\n\n### D1 Linked question?\nDisposition: OPEN.\nOriginal peer evidence.\n';writeFileSync(peer,peerSource);
 const rows=(await f.call('records?kind=decisions&refresh=1')).value.records,route='records?'+new URLSearchParams({kind:'decisions',key:rows[0].key});
 // Either linked narrative can represent the group. Exercise its actual peer,
 // independently of the library's asynchronous discovery/insertion order.
 const linked=(await f.call(route)).value.peers[0],linkedFile=path.join(f.repo,linked.path),linkedSource=readFileSync(linkedFile,'utf8');
 ok(linked.body.includes('Original peer evidence.'));
 writeFileSync(linkedFile,linkedSource.replace('Original peer evidence.','Fresh peer evidence.'));ok((await f.call(route)).value.peers.find(p=>p.path===linked.path).body.includes('Fresh peer evidence.'));
 writeFileSync(linkedFile,linkedSource.replace('### D1','\n### D1'));strictEqual((await f.call(route)).value.code,'decision-revision-conflict');
});
it('includes native alternatives and relationship hints while keeping legacy outcome writers separate',async()=>{
 const f=await fixture(),id=(kind,n)=>`${kind}:00000000-0000-4000-8000-${String(n).padStart(12,'0')}`,actor={kind:'human',id:'human:fixture'},at='2026-10-05T00:00:00Z',common={repository_id:id('repo',1),created_by:actor,aliases:[],evidence:[],relations:[],history:[]};
 const data={...common,options:[{id:id('option',4),label:'Blue bin',description:'Uses the shelf.',consequences:[{kind:'cost',text:'Requires a label.'}]},{id:id('option',5),label:'Red bin',description:'Needs a new shelf.',consequences:[{kind:'risk',text:'Less space.'}]}],recommendations:[],rulings:[],relations:[{id:id('relation',6),source_id:id('decision',3),kind:'about',by:actor,at,target:{id:id('plan',2),repository_id:id('repo',1),path:'docs/plans/fixture.md'}}]};
 const record=`---\nrecord_schema: runlist.record/v1\nid: ${id('decision',3)}\ntype: decision\nstatus: open\ncreated: ${at}\nupdated: ${at}\nquestion: Which native bin?\nrecord_data: |-\n${JSON.stringify(data,null,2).split('\n').map(l=>'  '+l).join('\n')}\n---\n# Native fixture\n\nContext.\n`;mkdirSync(path.join(f.repo,'docs/decisions'));writeFileSync(path.join(f.repo,'docs/decisions/native.md'),record);
 const rows=(await f.call('records?kind=decisions&refresh=1')).value.records,native=rows.find(r=>r.native);ok(native);strictEqual(native.title,'Which native bin?');const detail=(await f.call('records?'+new URLSearchParams({kind:'decisions',key:native.key}))).value;strictEqual(detail.editable,true);strictEqual(detail.data.options.length,2);strictEqual(detail.diagnostics.length,0,JSON.stringify(detail.diagnostics));ok(detail.connections.some(c=>c.path==='docs/plans/fixture.md'));strictEqual((await f.call('decisions/preview',{key:native.key,expectedRevision:detail.revision,disposition:'ruled',choice:'Blue bin',note:'Reason'})).value.code,'record-read-only');const cli=spawnSync(process.execPath,[bin,'decision','docs/decisions/native.md','D1','--disposition','held','--note','Reason'],{cwd:f.repo,encoding:'utf8'});ok(cli.status!==0);match(cli.stderr,/domain writer/);strictEqual(readFileSync(path.join(f.repo,'docs/decisions/native.md'),'utf8'),record);
});
