// Read-only, packaged-runtime workload. No forced GC or mutations.
import{spawn,execFileSync}from'node:child_process';import{readFileSync,mkdirSync}from'node:fs';import{randomUUID}from'node:crypto';import path from'node:path';import{once}from'node:events';import{checkoutTrust}from'../trust.mjs';
const engine=path.resolve(process.env.RUNLIST_MEASURE_ENGINE??path.resolve(import.meta.dirname,'../src-tauri/resources')),root=checkoutTrust(process.argv[2]).root,hash=checkoutTrust(root).fingerprint,version=JSON.parse(readFileSync(path.join(engine,'package.json'))).version;
const profile=process.env.RUNLIST_PROFILE_DIR?path.resolve(process.env.RUNLIST_PROFILE_DIR):null;if(profile)mkdirSync(profile,{recursive:true});
const child=spawn(path.join(engine,'runtime/RunlistHelper'),['--max-old-space-size=256','--max-semi-space-size=4',...(profile?['--cpu-prof',`--cpu-prof-dir=${profile}`]:[]),path.join(engine,'desktop/helper.mjs'),'--serve',root,hash],{env:{HOME:process.env.HOME,PATH:'/usr/bin:/bin:/usr/sbin:/sbin'},stdio:['pipe','pipe','ignore']});let buffer='',pending=new Map(),peak=0;const handle=randomUUID();
child.stdout.on('data',chunk=>{buffer+=chunk;let at;while((at=buffer.indexOf('\n'))>=0){const reply=JSON.parse(buffer.slice(0,at));buffer=buffer.slice(at+1);pending.get(reply.id)?.(reply);pending.delete(reply.id);}});
const sampler=setInterval(()=>{try{peak=Math.max(peak,Number(execFileSync('/bin/ps',['-o','rss=','-p',String(child.pid)],{encoding:'utf8'}).trim())*1024);}catch{}},250);
const call=(op,route)=>new Promise((resolve,reject)=>{const id=randomUUID(),timer=setTimeout(()=>reject(new Error('helper deadline')),75000);pending.set(id,result=>{clearTimeout(timer);result.ok?resolve(result.value):reject(new Error(result.error.message));});child.stdin.write(JSON.stringify({id,protocol:1,version,handle,op,...(route?{route:'/api/'+route}:{})})+'\n');});
const sample=async stage=>{const value=await call('metrics');peak=Math.max(peak,value.rss);console.log(JSON.stringify({stage,pid:child.pid,...Object.fromEntries(Object.entries(value).map(([k,v])=>[k,Math.round(v/104857.6)/10]))}));};
try{await call('hello');await sample('startup');for(let i=0;i<6;i++){for(const route of ['library?refresh=1','records?kind=flags&refresh=1','records?kind=decisions&status=']){const start=performance.now(),value=await call('request',route);console.log(JSON.stringify({cycle:i+1,route,elapsedMs:Math.round(performance.now()-start),total:value.total,counts:value.counts}));}await sample(`cycle-${i+1}`);}const docs=await call('request','library?limit=1');for(const documentPath of [...new Set([docs.documents[0]?.path,process.argv[3]].filter(Boolean))]){const start=performance.now(),doc=await call('request','document?'+new URLSearchParams({path:documentPath}));console.log(JSON.stringify({stage:'detail-load',elapsedMs:Math.round(performance.now()-start),sourceBytes:Buffer.byteLength(doc.source??'')}));}await sample('detail');console.log(JSON.stringify({sampledPeakRSSMiB:Math.round(peak/104857.6)/10,forcedGC:false}));}finally{clearInterval(sampler);child.stdin.end();await once(child,'exit');}
