import {mkdir,cp,rm,readFile,writeFile,chmod} from 'node:fs/promises';
import {existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {selectRuntime} from './runtime-target.mjs';
const desktop=fileURLToPath(new URL('../',import.meta.url)),repo=path.resolve(desktop,'..');
const version=JSON.parse(await readFile(path.join(repo,'package.json'),'utf8')).version;
const pin=JSON.parse(await readFile(path.join(desktop,'runtime-lock.json'),'utf8'));
const selected=selectRuntime(pin),{arch,platform}=selected;
const cache=path.join(desktop,'.cache');await mkdir(cache,{recursive:true});
const archive=path.join(cache,selected.file);
if(!existsSync(archive)){const response=await fetch(`https://nodejs.org/dist/${pin.version}/${selected.file}`);if(!response.ok)throw new Error('Runtime download failed.');const temporary=archive+'.download';await writeFile(temporary,Buffer.from(await response.arrayBuffer()));const bytes=await readFile(temporary);if(createHash('sha256').update(bytes).digest('hex')!==selected.sha256){await rm(temporary,{force:true});throw new Error('The pinned runtime checksum does not match.');}await cp(temporary,archive);await rm(temporary,{force:true});}
const digest=createHash('sha256').update(await readFile(archive)).digest('hex');if(digest!==selected.sha256)throw new Error('The pinned runtime checksum does not match.');
execFileSync('tar',['-xf',archive,'-C',cache],{windowsHide:true});
const runtime=path.join(cache,selected.folder);
const resources=path.join(desktop,'src-tauri','resources');await rm(resources,{recursive:true,force:true});await mkdir(path.join(resources,'desktop'),{recursive:true});
for(const name of ['src','bin','assets','package.json','LICENSE'])await cp(path.join(repo,name),path.join(resources,name),{recursive:true});
for(const name of ['helper.mjs','trust.mjs','line-framer.mjs'])await cp(path.join(desktop,name),path.join(resources,'desktop',name));
await cp(path.join(desktop,'node_modules/acorn'),path.join(resources,'desktop/node_modules/acorn'),{recursive:true});
await cp(path.join(runtime,'LICENSE'),path.join(resources,'NODE-LICENSE.txt'));
await mkdir(path.join(resources,'runtime'),{recursive:true});await cp(path.join(runtime,selected.nodePath),path.join(resources,'runtime',selected.executable));if(platform!=='win32')await chmod(path.join(resources,'runtime',selected.executable),0o755);
const dist=path.join(desktop,'dist');await rm(dist,{recursive:true,force:true});await cp(path.join(repo,'assets','app'),dist,{recursive:true});
await writeFile(path.join(resources,'bundle-manifest.json'),JSON.stringify({version,protocol:1,runtime:pin.version,architecture:arch,platform,target:selected.target,executable:selected.executable,runtimeSha256:digest},null,2)+'\n');
const configFile=path.join(desktop,'src-tauri','tauri.conf.json');const config=JSON.parse(await readFile(configFile,'utf8'));config.version=version;await writeFile(configFile,JSON.stringify(config,null,2)+'\n');
const cargoFile=path.join(desktop,'src-tauri/Cargo.toml');await writeFile(cargoFile,(await readFile(cargoFile,'utf8')).replace(/^(version\s*=\s*)"[^"]+"/m,`$1"${version}"`));
await import('./notices.mjs');
console.log(`Prepared Runlist ${version}, protocol 1, Node ${pin.version}, ${platform}/${arch}.`);
