import {test,afterEach} from 'node:test';
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {existsSync,mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,realpathSync,symlinkSync,readdirSync,readlinkSync} from 'node:fs';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {randomUUID} from 'node:crypto';
import {once} from 'node:events';
import {checkoutTrust} from '../trust.mjs';
import {sourceRevision} from '../../src/source-editor.mjs';
import {localActor} from '../../src/app-service.mjs';
import {parseNativeRecord} from '../../src/native-record.mjs';
import {nativeFixture,nativeSource,recordId} from '../../test/native-fixtures.mjs';
import {helperEnvironment} from './helper-environment.mjs';
import {commitPlatformQualified} from '../../src/git-commit-support.mjs';
const version=JSON.parse(readFileSync(new URL('../../package.json',import.meta.url))).version;
const runtime=process.env.RUNLIST_TEST_RUNTIME??process.execPath;
const entry=process.env.RUNLIST_TEST_HELPER??path.resolve(import.meta.dirname,'../helper.mjs');
const dirs=[],children=[];
afterEach(async()=>{for(const child of children.splice(0)){if(child.exitCode===null&&child.signalCode===null){child.stdin.end();await once(child,'exit');}}for(const dir of dirs.splice(0))rmSync(dir,{recursive:true,force:true});});
const source='---\r\ntype: plan\r\nstatus: active\r\ncustom: preserved\r\n---\r\n# Desktop fixture\r\n\r\nOriginal paragraph.\r\n\r\n## Version History\r\n\r\n- Existing history.\r\n';
function fixture(config="export const root='docs';\n") {const root=realpathSync(mkdtempSync(path.join(tmpdir(),'runlist-desktop-')));dirs.push(root);mkdirSync(path.join(root,'docs/plans'),{recursive:true});mkdirSync(path.join(root,'docs/prompts'));writeFileSync(path.join(root,'runlist.config.mjs'),config);writeFileSync(path.join(root,'docs/plans/fixture.md'),source);writeFileSync(path.join(root,'docs/prompts/private.md'),'PRIVATE PROMPT');return root;}
function helper(root,hash=checkoutTrust(root).fingerprint,environment={}) {
 const child=spawn(runtime,[entry,'--serve',root,hash],{env:helperEnvironment({CODEX_THREAD_ID:'agent-must-not-be-actor',...environment}),windowsHide:true,stdio:['pipe','pipe','pipe']});children.push(child);let buffer='',pending=new Map();const handle=randomUUID();
 child.stdout.setEncoding('utf8'); // Preserve code points split across pipe chunks.
 child.stdout.on('data',chunk=>{buffer+=chunk;let end;while((end=buffer.indexOf('\n'))>=0){const reply=JSON.parse(buffer.slice(0,end));buffer=buffer.slice(end+1);pending.get(reply.id)?.(reply);pending.delete(reply.id);}});
 const call=(op,route,body,extra={},fragmentBytes=0)=>new Promise((resolve,reject)=>{const id=randomUUID(),timer=setTimeout(()=>reject(new Error('helper response timeout')),10000);pending.set(id,result=>{clearTimeout(timer);resolve(result);});const wire=Buffer.from(JSON.stringify({protocol:1,version,id,handle,op,...(route?{route}:{}),...(body!==undefined?{body}:{}),...extra})+'\n');if(fragmentBytes){for(let i=0;i<wire.length;i+=fragmentBytes)child.stdin.write(wire.subarray(i,i+fragmentBytes));}else child.stdin.write(wire);});
 return {child,call,handle,hello:()=>call('hello'),request:(route,body,extra)=>call('request','/api/'+route,body,extra),fragmentedRequest:(route,body)=>call('request','/api/'+route,body,{},4093)};
}
test('probe does not execute configuration; imports and package metadata renew trust',()=>{const root=fixture("import {root} from './settings.mjs';\nexport {root};\nthrow new Error('must not execute during discovery');\n");writeFileSync(path.join(root,'settings.mjs'),"export const root='docs';\n");const first=checkoutTrust(root);assert.equal(first.files.length,2);writeFileSync(path.join(root,'settings.mjs'),"export const root='other';\n");assert.notEqual(checkoutTrust(root).fingerprint,first.fingerprint);});
test('trust rejects escaping and symlink dependencies, and marks dynamic imports',()=>{const root=fixture("import './settings.mjs';\n");const other=fixture();symlinkSync(path.join(other,'runlist.config.mjs'),path.join(root,'settings.mjs'));assert.throws(()=>checkoutTrust(root),/without symlinks/);writeFileSync(path.join(root,'runlist.config.mjs'),"const x='optional';\nexport const hook=()=>import(x);\n");assert.equal(checkoutTrust(root).volatile,true);});
test('trust parses multiline imports, escaped specifiers and reexports without treating comments as code',()=>{const root=fixture("// import './does-not-exist.mjs';\nimport {\n root\n} from './settings.mjs';\nexport {other} from './\\u006ft her.mjs';\nexport {root};\n");writeFileSync(path.join(root,'settings.mjs'),"export const root='docs';\n");writeFileSync(path.join(root,'ot her.mjs'),"export const other=1;\n");const before=checkoutTrust(root);assert.equal(before.files.length,3);assert.equal(before.volatile,false);writeFileSync(path.join(root,'ot her.mjs'),"export const other=2;\n");assert.notEqual(checkoutTrust(root).fingerprint,before.fingerprint);});
test('concatenated dynamic imports and aliased loaders require renewed trust',()=>{const root=fixture("const name='settings';\nexport const hook=()=>import('./'+name+'.mjs');\n");assert.equal(checkoutTrust(root).volatile,true);writeFileSync(path.join(root,'runlist.config.mjs'),"import {createRequire} from 'node:module';\nconst load=createRequire(import.meta.url);\nexport const hook=()=>load('./settings.cjs');\n");assert.equal(checkoutTrust(root).volatile,true);});
test('a malformed native handle cannot execute configuration during hello',async()=>{const root=fixture("throw new Error('MUST NOT EXECUTE');\n"),h=helper(root);assert.equal((await h.call('hello',undefined,undefined,{handle:'invalid'})).error.code,'invalid-handle');});
test('checkout diagnostics cannot corrupt reserved protocol stdout',async()=>{const root=fixture("console.dir({message:'configuration diagnostic'});\nprocess.stdout.write('ordinary checkout log\\n');\nexport const root='docs';\n"),h=helper(root);let diagnostics='';h.child.stderr.on('data',chunk=>diagnostics+=chunk);assert.equal((await h.hello()).ok,true);assert.equal((await h.request('library')).ok,true);assert.match(diagnostics,/configuration diagnostic/);assert.match(diagnostics,/ordinary checkout log/);});
test('helper authenticates a human independently of the agent and rejects forged handles/actors/routes',async()=>{const root=fixture(),h=helper(root);assert.deepEqual((await h.hello()).value.actor,localActor());assert.equal((await h.request('library',undefined,{handle:randomUUID()})).error.code,'forbidden');assert.equal((await h.request('save',{actor:{kind:'agent'}})).error.code,'forbidden');assert.equal((await h.request('shell',{command:'echo invalid'})).error.code,'not-found');assert.equal((await h.request('document?path=../escape.md')).ok,false);assert.equal((await h.request('document?path=docs/prompts/private.md')).ok,false);assert.equal((await h.call('request','/api/library',undefined,{protocol:999})).error.code,'protocol-mismatch');});
test('native helper shares read-only Changes authority and preserves HEAD/index on status and diff',async()=>{
 const root=fixture(),git=args=>{const result=spawnSync('git',['-c','commit.gpgsign=false','-C',root,...args],{encoding:'utf8',env:{PATH:process.env.PATH,GIT_CONFIG_NOSYSTEM:'1',GIT_CONFIG_GLOBAL:process.platform==='win32'?'NUL':'/dev/null'}});assert.equal(result.status,0,result.stderr);return result.stdout;};
 git(['init','-q','-b','main']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@invalid.example']);git(['add','--','docs/plans/fixture.md']);git(['commit','-qm','fixture']);writeFileSync(path.join(root,'docs/plans/fixture.md'),source.replace('Original','Saved for Git review'));
 const index=readFileSync(path.join(root,'.git/index')),head=git(['rev-parse','HEAD']),h=helper(root);await h.hello();const status=await h.request('git/status');assert.equal(status.ok,true);assert.equal(status.value.available,true);assert.equal(status.value.commitEnabled,false);const diff=await h.request('git/diff?path=docs/plans/fixture.md');assert.equal(diff.ok,true);assert.match(diff.value.after,/Saved for Git review/);
 assert.equal((await h.request('git/diff?path=docs/prompts/private.md')).error.code,'forbidden');assert.equal((await h.request('git/status',undefined,{handle:randomUUID()})).error.code,'forbidden');assert.equal((await h.request('git/commit',{paths:['docs/plans/fixture.md']})).error.code,'not-found');assert.deepEqual(readFileSync(path.join(root,'.git/index')),index);assert.equal(git(['rev-parse','HEAD']),head);
});
test('unapproved or changed configuration is never imported',async()=>{const root=fixture("throw new Error('DO NOT IMPORT');\n"),h=helper(root,'0'.repeat(64));assert.equal((await h.hello()).error.code,'trust-changed');const safe=fixture(),current=helper(safe);assert.equal((await current.hello()).ok,true);writeFileSync(path.join(safe,'runlist.config.mjs'),"throw new Error('DO NOT IMPORT CHANGED CODE');\n");assert.equal((await current.request('library')).error.code,'trust-changed');});
test('private pipe saves exact source, preserves receipt through lost reply/restart, rejects external edit and undoes',async()=>{const root=fixture(),h=helper(root);await h.hello();const doc=(await h.request('document?path=docs/plans/fixture.md')).value;assert.equal(doc.source,source);const request={path:doc.path,operationId:randomUUID(),expectedRevision:doc.revision,source:source.replace('Original','Saved through desktop')};const first=await h.request('save',request);assert.equal(first.ok,true);assert.equal(readFileSync(path.join(root,doc.path),'utf8'),request.source);h.child.stdin.end();await once(h.child,'exit');const next=helper(root);await next.hello();assert.equal((await next.request('save',request)).value.replayed,true);const retained=(await next.request('operation/inspect',{operationId:request.operationId})).value;assert.equal(retained.before,source);assert.equal((await next.request('undo',{path:doc.path,operationId:randomUUID(),undoOf:request.operationId,expectedRevision:first.value.revision})).ok,true);assert.equal(readFileSync(path.join(root,doc.path),'utf8'),source);writeFileSync(path.join(root,doc.path),source.replace('Original','External'));assert.equal((await next.request('save',{...request,operationId:randomUUID()})).error.code,'revision-conflict');});
test('fragmented large Unicode draft/save frames preserve bytes and retained recovery evidence',async()=>{
 const root=fixture(),file='docs/plans/large.md',before='---\r\ntype: plan\r\nstatus: active\r\n---\r\n'+('Large source 先 🧭 with Unicode.\r\n'.repeat(70000));
 writeFileSync(path.join(root,file),before);const h=helper(root);await h.hello();
 const doc=(await h.request('document?path='+file)).value,after=before+'\r\nSaved 先 🧭.\r\n',draftId=randomUUID();
 const draft=await h.fragmentedRequest('draft/write',{path:file,draftId,expectedDraftRevision:null,baseSource:before,baseRevision:doc.revision,source:after});
 assert.equal(draft.ok,true);assert.equal((await h.request('draft/read',{path:file,draftId})).value.source,after);
 const operationId=randomUUID(),saved=await h.fragmentedRequest('save',{path:file,operationId,expectedRevision:doc.revision,source:after});
 assert.equal(saved.ok,true);assert.deepEqual(readFileSync(path.join(root,file)),Buffer.from(after));
 const retained=(await h.request('operation/inspect',{operationId})).value;assert.equal(retained.before,before);assert.equal(retained.after,after);
 assert.equal((await h.request('draft/discard',{path:file,draftId,expectedDraftRevision:draft.value.revision})).ok,true);
});
test('packaged helper keeps Git checkouts read-only when private storage cannot be verified without Git',async()=>{
 const root=fixture();const initialized=spawnSync('git',['init','-q',root],{encoding:'utf8'});assert.equal(initialized.status,0,initialized.stderr);
 writeFileSync(path.join(root,'.gitignore'),'');const emptyPath=path.join(root,'empty-path');mkdirSync(emptyPath);
 const h=helper(root,undefined,{PATH:emptyPath});assert.equal((await h.hello()).ok,true);
 const opened=await h.request('document?path=docs/plans/fixture.md');assert.equal(opened.ok,true);const doc=opened.value;
 const draft=await h.request('draft/write',{path:doc.path,draftId:randomUUID(),expectedDraftRevision:null,baseSource:doc.source,baseRevision:doc.revision,source:doc.source.replace('Original','Private draft')});
 assert.equal(draft.error?.code,'unsafe-local-state',JSON.stringify(draft));
 const saved=await h.request('save',{path:doc.path,operationId:randomUUID(),expectedRevision:doc.revision,source:doc.source.replace('Original','Saved')});
 assert.equal(saved.error?.code,'unsafe-local-state',JSON.stringify(saved));
 const lifecycle=await h.request('lifecycle/commit',{operationId:randomUUID()});assert.equal(lifecycle.error?.code,'unsafe-local-state',JSON.stringify(lifecycle));
 assert.equal(readFileSync(path.join(root,doc.path),'utf8'),source);assert.equal(existsSync(path.join(root,'.runlist/editor')),false);
});
test('bundled helper discovers Git and keeps saved before-images private',async()=>{
 const root=fixture();const git=args=>{const result=spawnSync('git',['-C',root,...args],{encoding:'utf8',windowsHide:true});assert.equal(result.status,0,result.stderr);return result.stdout;};
 git(['init','-q']);writeFileSync(path.join(root,'.gitignore'),'.runlist/\n.dotmd/\n');
 const h=helper(root);assert.equal((await h.hello()).ok,true);const doc=(await h.request('document?path=docs/plans/fixture.md')).value;
 const request={path:doc.path,operationId:randomUUID(),expectedRevision:doc.revision,source:source.replace('Original','Git-verified save')};
 const saved=await h.request('save',request);assert.equal(saved.ok,true,JSON.stringify(saved));assert.equal(readFileSync(path.join(root,doc.path),'utf8'),request.source);
 const retained=await h.request('operation/inspect',{operationId:request.operationId});assert.equal(retained.ok,true,JSON.stringify(retained));assert.equal(retained.value.before,source);
 assert.doesNotMatch(git(['status','--porcelain','--untracked-files=all']),/editor|before-image|Git-verified save/);
});
test('installed helper crash retains unpublished draft, detects external edits and prevents stale draft overwrite',async()=>{const root=fixture(),h=helper(root);await h.hello();const doc=(await h.request('document?path=docs/plans/fixture.md')).value,request={path:doc.path,draftId:randomUUID(),expectedDraftRevision:null,baseSource:doc.source,baseRevision:doc.revision,source:doc.source.replace('Original','Unpublished recoverable draft')};const stored=await h.request('draft/write',request);assert.equal(stored.ok,true,JSON.stringify(stored));assert.equal(readFileSync(path.join(root,doc.path),'utf8'),source);const exited=once(h.child,'exit');h.child.kill('SIGKILL');await exited;const reopened=helper(root);await reopened.hello();const recovered=await reopened.request('draft/read',{path:doc.path,draftId:request.draftId});assert.equal(recovered.ok,true);assert.equal(recovered.value.source,request.source);assert.equal(recovered.value.stale,false);assert.equal(readFileSync(path.join(root,doc.path),'utf8'),source);writeFileSync(path.join(root,doc.path),source.replace('Original','External editor'));assert.equal((await reopened.request('draft/read',{path:doc.path,draftId:request.draftId})).value.stale,true);assert.equal((await reopened.request('draft/write',{...request,source:'Stale overwrite'})).error.code,'draft-conflict');assert.equal((await reopened.request('draft/read',{path:doc.path,draftId:request.draftId})).value.source,request.source);});
test('EOF drains an accepted save and stops the helper; no socket listener exists',async()=>{const root=fixture(),h=helper(root);await h.hello();if(process.platform==='darwin'){const sockets=spawnSync('/usr/sbin/lsof',['-a','-p',String(h.child.pid),'-i'],{encoding:'utf8'});assert.equal(sockets.stdout.trim(),'');}if(process.platform==='linux'){
 const fd=path.join('/proc',String(h.child.pid),'fd');
 const owned=new Set(readdirSync(fd).flatMap(name=>{try{const target=readlinkSync(path.join(fd,name));return /^socket:\[(\d+)\]$/.exec(target)?.slice(1)??[];}catch(error){if(error.code==='ENOENT')return [];throw error;}}));
 // Node's stdio pipes use connected Unix socket pairs on Linux. Only unnamed,
 // non-listening Unix sockets are allowed; reject every owned TCP/UDP socket.
 for(const table of ['tcp','tcp6','udp','udp6'])for(const row of readFileSync(`/proc/${h.child.pid}/net/${table}`,'utf8').trim().split('\n').slice(1)){const fields=row.trim().split(/\s+/);assert.equal(owned.has(fields[9]),false,`Helper owns a ${table} socket.`);}
 const unix=new Map(readFileSync(`/proc/${h.child.pid}/net/unix`,'utf8').trim().split('\n').slice(1).map(row=>{const fields=row.trim().split(/\s+/);return [fields[6],fields];}));
 for(const inode of owned){const fields=unix.get(inode);assert.ok(fields,'Every helper socket must be a private Unix stream.');assert.equal(fields[3],'00000000','Helper must not own a Unix listener.');assert.equal(fields[7],undefined,'Private streams must not bind a filesystem/abstract address.');}
 }const request={path:'docs/plans/fixture.md',operationId:randomUUID(),expectedRevision:sourceRevision(source),source:source.replace('Original','EOF accepted')};const exited=once(h.child,'exit'),promise=h.request('save',request);h.child.stdin.end();assert.equal((await promise).ok,true);await exited;assert.equal(readFileSync(path.join(root,request.path),'utf8'),request.source);});
test('invalid versions and oversized protocol input cannot mutate a checkout',async()=>{const root=fixture(),h=helper(root);await h.hello();assert.equal((await h.call('request','/api/library',undefined,{version:'invalid'})).error.code,'protocol-mismatch');h.child.stdin.on('error',()=>{});const exited=once(h.child,'exit');h.child.stdin.end('x'.repeat(32*1024*1024+1)+'\n');await exited;assert.equal(readFileSync(path.join(root,'docs/plans/fixture.md'),'utf8'),source);});
test('packaged schemas, native decision/flag reviews, templates and Settings share local authority',async()=>{const root=fixture("export const root='docs';\nexport const validTypes=['plan','doc','flag','decision'];\n"),h=helper(root);for(const type of ['decisions','flags'])mkdirSync(path.join(root,'docs',type));const decision='docs/decisions/native.md',flag='docs/flags/native.md';writeFileSync(path.join(root,decision),nativeSource());writeFileSync(path.join(root,flag),nativeSource(nativeFixture('flag')));const actor=(await h.hello()).value.actor;
 for(const [file,action,optionId] of [[decision,'ruled',recordId('option',4)],[flag,'reject',undefined]]){const doc=(await h.request('document?'+new URLSearchParams({path:file}))).value,review=await h.request('native/preview',{path:file,expectedRevision:doc.revision,operationId:randomUUID(),action,optionId,note:'Desktop packaged verification'});assert.equal(review.ok,true,JSON.stringify(review));assert.equal(readFileSync(path.join(root,file),'utf8'),doc.source);const saved=await h.request('native/action',review.value.request);assert.equal(saved.ok,true,JSON.stringify(saved));assert.equal((await h.request('native/action',review.value.request)).value.replayed,true);const record=parseNativeRecord(readFileSync(path.join(root,file),'utf8'));assert.equal(record.ok,true);assert.equal(record.record.custom_team,'original');assert.equal(record.record.record_data.history.at(-1).by.id,actor.id);}
 assert.equal((await h.request('records?kind=decisions&status=ruled')).value.records.length,1);assert.equal((await h.request('records?kind=flags&status=closed')).value.records.length,1);const catalog=(await h.request('templates')).value,plan=catalog.templates.find(t=>t.name==='plan'),edited=plan.source+'\n<!-- Desktop template -->\n',templates=await h.request('templates/save',{name:'plan',source:edited,expectedRevision:catalog.revision});assert.equal(templates.ok,true,JSON.stringify(templates));assert.equal(templates.value.templates.find(t=>t.name==='plan').source,edited);assert.equal((await h.request('settings')).value.sharing.preferences,'This computer · Runlist desktop');
});
test('CLI desktop launch previews without executing checkout configuration',()=>{const root=fixture("throw new Error('CLI MUST NOT LOAD CONFIG');\n");const result=spawnSync(runtime,[path.resolve(import.meta.dirname,'../../bin/runlist.mjs'),'desktop','--dry-run'],{cwd:root,encoding:'utf8',windowsHide:true});assert.equal(result.status,0,result.stderr);assert.match(result.stdout,/No server starts/);});
test('bundled lifecycle worker uses the bundled executable and commits reviewed CLI transitions',async()=>{const root=fixture("import {writeFileSync} from 'node:fs';\nexport const root='docs';\nexport function onStatusChange(){writeFileSync(new URL('worker-runtime',import.meta.url),process.execPath);}\n"),h=helper(root);await h.hello();const doc=(await h.request('document?path=docs/plans/fixture.md')).value;const id=randomUUID();const preview=await h.request('lifecycle/preview',{path:doc.path,status:'planned',note:'Native runtime verification',expectedRevision:doc.revision,operationId:id});assert.equal(preview.ok,true,JSON.stringify(preview));const commit=await h.request('lifecycle/commit',{operationId:id});assert.equal(commit.ok,true,JSON.stringify(commit));assert.equal(commit.value.state,'committed');assert.equal(realpathSync(readFileSync(path.join(root,'worker-runtime'),'utf8')),realpathSync(runtime));assert.match(readFileSync(path.join(root,doc.path),'utf8'),/status: planned/);assert.equal((await h.request('lifecycle/commit',{operationId:id})).value.replayed,true);});

test('bundled helper supports reviewed creation, content search and disk recovery over private pipes',async()=>{
 const root=fixture(),h=helper(root);await h.hello();
 const catalog=await h.request('create');assert.equal(catalog.ok,true);assert.ok(catalog.value.templates.some(t=>t.name==='hub'));
 const operationId=randomUUID(),preview=await h.request('create/preview',{operationId,template:'doc',folder:'docs',filename:'workspace-created.md',title:'Workspace created',status:'active',body:'bundled_workspace_needle'});
 assert.equal(preview.ok,true,JSON.stringify(preview));assert.equal(existsSync(path.join(root,'docs/workspace-created.md')),false);
 const committed=await h.request('create/commit',{operationId});assert.equal(committed.ok,true,JSON.stringify(committed));assert.equal(readFileSync(path.join(root,'docs/workspace-created.md'),'utf8'),preview.value.source);
 const search=await h.request('search?q=bundled_workspace_needle');assert.equal(search.ok,true,JSON.stringify(search));assert.equal(search.value.documents[0].path,'docs/workspace-created.md');
 const doc=(await h.request('document?path=docs/workspace-created.md')).value,id=randomUUID(),draftId=randomUUID();
 const saved=await h.request('draft/write',{path:doc.path,draftId,expectedDraftRevision:null,baseRevision:doc.revision,baseSource:doc.source,source:doc.source.replace('bundled_workspace_needle','Unpublished disk recovery'),pendingOperation:{kind:'save',operationId:id,expectedRevision:doc.revision}});assert.equal(saved.ok,true,JSON.stringify(saved));
 const recovery=await h.request('recovery');assert.equal(recovery.ok,true,JSON.stringify(recovery));assert.equal(recovery.value.items.find(i=>i.draftId===draftId).pendingOperation.operationId,id);assert.ok(!JSON.stringify(recovery.value).includes('Unpublished disk recovery'));
 assert.equal((await h.request('create/commit',{operationId})).value.replayed,true);
});
test('private helper pipe creates native flags and decisions with server authority and persisted identity',async()=>{
 const root=fixture(),h=helper(root);assert.equal((await h.hello()).ok,true);let repositoryId;
 for(const type of ['flag','decision']){
  const operationId=randomUUID(),request={operationId,template:type,title:type==='flag'?'Missing fixture label':'Which fixture label?',status:'open',folder:`docs/records/${type==='flag'?'flags':'decisions'}`,filename:randomUUID()+'.md',body:'Fixture context.',...(type==='flag'?{severity:'info'}:{options:[{label:'Blue',description:'Current label.',consequences:[]},{label:'Red',description:'Replacement label.',consequences:[]}]})};
  const reviewed=await h.request('create/preview',request);assert.equal(reviewed.ok,true,JSON.stringify(reviewed));assert.equal(existsSync(path.join(root,reviewed.value.path)),false);assert.equal(reviewed.value.record.record_data.created_by.id,localActor().id);
  const committed=await h.request('create/commit',{operationId});assert.equal(committed.ok,true,JSON.stringify(committed));assert.equal(committed.value.record.id,reviewed.value.record.id);const parsed=parseNativeRecord(readFileSync(path.join(root,reviewed.value.path),'utf8'));assert.equal(parsed.ok,true);repositoryId??=parsed.record.record_data.repository_id;assert.equal(parsed.record.record_data.repository_id,repositoryId);
  const detail=await h.request('records?'+new URLSearchParams({kind:type==='flag'?'flags':'decisions',key:parsed.record.id}));assert.equal(detail.ok,true);assert.equal(detail.value.editable,true);assert.equal((await h.request('create/commit',{operationId})).value.replayed,true);
 }
 assert.equal(JSON.parse(readFileSync(path.join(root,'runlist.records.json'),'utf8')).repositoryId,repositoryId);
});

test('native Git jobs return promptly, survive helper shutdown and expose one verified local commit',{skip:!commitPlatformQualified()},async()=>{
 const root=fixture(),home=path.join(root,'isolated-home');mkdirSync(home);writeFileSync(path.join(root,'.gitignore'),'.runlist/\n.dotmd/\n');
 const git=args=>{const q=spawnSync('git',['-C',root,...args],{encoding:'utf8',env:{PATH:process.env.PATH,HOME:home,LANG:'C',LC_ALL:'C'}});assert.equal(q.status,0,q.stderr);return q.stdout.trim();};
 git(['init','-q','-b','main']);git(['config','user.name','Fixture']);git(['config','user.email','fixture@invalid.example']);git(['config','commit.gpgSign','false']);git(['add','docs/plans/fixture.md','runlist.config.mjs','.gitignore']);git(['commit','-qm','base']);
 const key=path.join(root,'fixture-signing-key'),generated=spawnSync('/usr/bin/ssh-keygen',['-q','-t','ed25519','-N','','-f',key],{encoding:'utf8'});assert.equal(generated.status,0,generated.stderr);git(['config','commit.gpgSign','true']);git(['config','gpg.format','ssh']);git(['config','user.signingkey',key]);writeFileSync(path.join(root,'.git/hooks/pre-commit'),'#!/bin/sh\nprintf hook-ran > native-hook-marker\n',{mode:0o700});
 const filter=path.join(root,'native-clean');writeFileSync(filter,'#!/bin/sh\nsed "s/Native local commit/Canonical native commit/g"\n',{mode:0o700});git(['config','filter.docs.clean',filter]);git(['config','filter.docs.required','true']);writeFileSync(path.join(root,'.gitattributes'),'*.md filter=docs\n');
 writeFileSync(path.join(root,'docs/plans/fixture.md'),source.replace('Original','Native local commit'));const h=helper(root,checkoutTrust(root).fingerprint,{HOME:home});assert.equal((await h.hello()).ok,true);
 const id=randomUUID(),start=await h.request('git/commit/preview',{operationId:id,paths:['docs/plans/fixture.md'],message:'Native documents'});assert.equal(start.ok,true,JSON.stringify(start));assert.equal(start.value.running,true);assert.equal((await h.call('metrics')).ok,true);
 async function settled(current){for(let i=0;i<500;i++){const response=await current.request('git/operation?id='+id);assert.equal(response.ok,true,JSON.stringify(response));if(!response.value.running)return response.value;await new Promise(resolve=>setTimeout(resolve,50));}assert.fail('native Git job did not settle');}
 const r=await settled(h);assert.equal(r.state,'reviewed',JSON.stringify(r));assert.equal(r.execution.signing,'ssh');assert.deepEqual(r.execution.filters,['docs']);assert.match(r.review[0].after,/Canonical native commit/);assert.ok(r.execution.hooks.includes('pre-commit'));assert.equal(existsSync(path.join(root,'native-hook-marker')),false);assert.equal((await h.request('git/commit/start',{operationId:id})).ok,true);
 const exited=once(h.child,'exit');h.child.stdin.end();await exited;
 const second=helper(root,checkoutTrust(root).fingerprint,{HOME:home});assert.equal((await second.hello()).ok,true);const done=await settled(second);assert.equal(done.state,'committed',JSON.stringify(done));assert.equal(done.indexReady,true);assert.equal(git(['rev-parse','HEAD']),done.commitId);assert.equal(git(['rev-list','--count','HEAD']),'2');assert.equal((await second.request('git/commit/start',{operationId:id})).value.commitId,done.commitId);
 assert.equal(readFileSync(path.join(root,'native-hook-marker'),'utf8'),'hook-ran');assert.match(git(['show','HEAD:docs/plans/fixture.md']),/Canonical native commit/);assert.match(readFileSync(path.join(root,'docs/plans/fixture.md'),'utf8'),/Native local commit/);assert.match(git(['cat-file','commit',done.commitId]),/gpgsig -----BEGIN SSH SIGNATURE-----/);
 assert.equal((await second.request('git/operation?id='+id,undefined,{handle:randomUUID()})).error.code,'forbidden');assert.equal((await second.request('git/commit/start',{operationId:id,actor:{kind:'human',id:'forged'}})).error.code,'forbidden');
});
test('yardstick and filing use authenticated private helper requests without a listening server',async()=>{
 const root=fixture("export const root='docs';\nexport const yardstick='docs/goal.md';\nexport const filing=true;\n");writeFileSync(path.join(root,'docs/goal.md'),'# Goal\n\nKeep useful project documents.\n');
 writeFileSync(path.join(root,'docs/hub.md'),'---\ntype: plan\nstatus: active\nexecution_mode: coordination\n---\n# Hub\n\n### Delivery\n| Plan | Status |\n|---|---|\n| [Fixture](plans/fixture.md) | active |\n');
 const h=helper(root);assert.equal((await h.hello()).ok,true);assert.equal((await h.request('filing?op=status')).value.state,'idle');
 let scan=(await h.request('filing?op=start&refresh=1')).value;while(scan.state==='scanning')scan=(await h.request('filing?op=advance&scanId='+scan.scanId)).value;assert.equal(scan.totals.filedDirect,1);
 const doc=(await h.request('document?path=docs/plans/fixture.md')).value;assert.equal((await h.request('yardstick?path='+doc.path)).value.enabled,true);
 const review=await h.request('yardstick/preview',{path:doc.path,action:'serves',reason:'Human choice.',expectedRevision:doc.revision,operationId:randomUUID()});assert.equal(review.ok,true);assert.equal((await h.request('yardstick/commit',{operationId:review.value.operationId})).value.state,'committed');
 assert.equal((await h.request('filing?op=status')).value.state,'idle');assert.match(readFileSync(path.join(root,doc.path),'utf8'),/yardstick_disposition: "serves"/);
 const native=readFileSync(new URL('../src-tauri/src/lib.rs',import.meta.url),'utf8');for(const route of ['yardstick','filing','yardstick/preview','yardstick/commit','yardstick/inspect','yardstick/settle'])assert.ok(native.includes('"'+route+'"'));
});
